# coding=utf-8
from OTLModel.Datatypes.Keuzelijst import Keuzelijst


# Generated with OTLEnumerationCreator. To modify: extend, do not edit
class KlBuisbekledingUitvoeringswijze(Keuzelijst):
    """Materiaal en manier van aanbrengen van de buisbekleding."""

    def __init__(self):
        super().__init__(naam="KlBuisbekledingUitvoeringswijze",
                         label="uitvoeringswijze buisbekleding",
                         objectUri="https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KlBuisbekledingUitvoeringswijze",
                         definition="Materiaal en manier van aanbrengen van de buisbekleding.",
                         usagenote="",
                         deprecated_version="",
                         codelist="https://wegenenverkeer.data.vlaanderen.be/id/conceptscheme/KlBuisbekledingUitvoeringswijze")

        self.add_option("bouwput-voor-rioolrenovatie-dmv-buis-in-buissysteem-met-glasvezelversterkte-polyesterelementen", "bouwput voor rioolrenovatie dmv buis in buissysteem met glasvezelversterkte polyesterelementen", "Bouwput voor rioolrenovatie dmv buis in buissysteem met glasvezelversterkte polyesterelementen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/bouwput-voor-rioolrenovatie-dmv-buis-in-buissysteem-met-glasvezelversterkte-polyesterelementen")
        self.add_option("buis-in-buis-renovatie-met-hard-PVC-wikkelbuizen.-profiel-nr.-140", "buis in buis renovatie met hard-PVC-wikkelbuizen. profiel nr. 140", "Buis in buis renovatie met hard-PVC-wikkelbuizen, profiel nr. 140", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/buis-in-buis-renovatie-met-hard-PVC-wikkelbuizen.-profiel-nr.-140")
        self.add_option("buis-in-buis-renovatie-met-hard-PVC-wikkelbuizen.-profiel-nr.-50", "buis in buis renovatie met hard-PVC-wikkelbuizen. profiel nr. 50", "Buis in buis renovatie met hard-PVC-wikkelbuizen, profiel nr. 50", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/buis-in-buis-renovatie-met-hard-PVC-wikkelbuizen.-profiel-nr.-50")
        self.add_option("buis-in-buis-renovatie-met-hard-PVC-wikkelbuizen.-profiel-nr.-60", "buis in buis renovatie met hard-PVC-wikkelbuizen. profiel nr. 60", "Buis in buis renovatie met hard-PVC-wikkelbuizen, profiel nr. 60", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/buis-in-buis-renovatie-met-hard-PVC-wikkelbuizen.-profiel-nr.-60")
        self.add_option("buis-in-buis-renovatie-met-hard-PVC-wikkelbuizen.-profiel-nr.-90", "buis in buis renovatie met hard-PVC-wikkelbuizen. profiel nr. 90", "Buis in buis renovatie met hard-PVC-wikkelbuizen, profiel nr. 90", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/buis-in-buis-renovatie-met-hard-PVC-wikkelbuizen.-profiel-nr.-90")
        self.add_option("buis-in-buis-renovatie-met-standaardbuizen-in-GVP.-sterktereeks-SN-10000-N-mm2", "buis in buis renovatie met standaardbuizen in GVP. sterktereeks SN 10000 N-mm2", "Buis in buis renovatie met standaardbuizen in GVP, sterktereeks SN 10000 N/mm2", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/buis-in-buis-renovatie-met-standaardbuizen-in-GVP.-sterktereeks-SN-10000-N-mm2")
        self.add_option("buis-in-buis-renovatie-met-standaardbuizen-in-GVP.-sterktereeks-SN-2500-N-mm2", "buis in buis renovatie met standaardbuizen in GVP. sterktereeks SN 2500 N-mm2", "Buis in buis renovatie met standaardbuizen in GVP, sterktereeks SN 2500 N/mm2", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/buis-in-buis-renovatie-met-standaardbuizen-in-GVP.-sterktereeks-SN-2500-N-mm2")
        self.add_option("buis-in-buis-renovatie-met-standaardbuizen-in-GVP.-sterktereeks-SN-5000-N-mm2", "buis in buis renovatie met standaardbuizen in GVP. sterktereeks SN 5000 N-mm2", "Buis in buis renovatie met standaardbuizen in GVP, sterktereeks SN 5000 N/mm2", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/buis-in-buis-renovatie-met-standaardbuizen-in-GVP.-sterktereeks-SN-5000-N-mm2")
        self.add_option("buis-in-buis-renovatie.-met-wandversterkte-HDPE-buizen", "buis in buis renovatie. met wandversterkte HDPE-buizen", "Buis in buis renovatie, met wandversterkte HDPE-buizen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/buis-in-buis-renovatie.-met-wandversterkte-HDPE-buizen")
        self.add_option("gunitage-via-de-natte-spuitmethode.-met-wapening.-glad-oppervlak", "gunitage via de natte spuitmethode. met wapening. glad oppervlak", "Gunitage via de natte spuitmethode, met wapening, glad oppervlak", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/gunitage-via-de-natte-spuitmethode.-met-wapening.-glad-oppervlak")
        self.add_option("gunitage-via-de-natte-spuitmethode.-met-wapening.-ruw-oppervlak", "gunitage via de natte spuitmethode. met wapening. ruw oppervlak", "Gunitage via de natte spuitmethode, met wapening, ruw oppervlak", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/gunitage-via-de-natte-spuitmethode.-met-wapening.-ruw-oppervlak")
        self.add_option("gunitage-via-de-natte-spuitmethode.-zonder-wapening.-glad-oppervlak", "gunitage via de natte spuitmethode. zonder wapening. glad oppervlak", "Gunitage via de natte spuitmethode, zonder wapening, glad oppervlak", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/gunitage-via-de-natte-spuitmethode.-zonder-wapening.-glad-oppervlak")
        self.add_option("gunitage-via-de-natte-spuitmethode.-zonder-wapening.-ruw-oppervlak", "gunitage via de natte spuitmethode. zonder wapening. ruw oppervlak", "Gunitage via de natte spuitmethode, zonder wapening, ruw oppervlak", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/gunitage-via-de-natte-spuitmethode.-zonder-wapening.-ruw-oppervlak")
        self.add_option("herstelling-van-lekkende-voegverbindingen-en-grindnesten-door-middel-van-het-plaatsen-van-inox-manchetten-in-buisleidingen", "herstelling van lekkende voegverbindingen en grindnesten door middel van het plaatsen van inox manchetten in buisleidingen", "Herstelling van lekkende voegverbindingen en grindnesten door middel van het plaatsen van inox manchetten in buisleidingen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/herstelling-van-lekkende-voegverbindingen-en-grindnesten-door-middel-van-het-plaatsen-van-inox-manchetten-in-buisleidingen")
        self.add_option("inwendige-bekleding-met-PUR-verf-voor-buizen-van-nodulair-gietijzer", "inwendige bekleding met PUR-verf voor buizen van nodulair gietijzer", "inwendige bekleding met PUR-verf voor buizen van nodC3:C48ulair gietijzer", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/inwendige-bekleding-met-PUR-verf-voor-buizen-van-nodulair-gietijzer")
        self.add_option("pipebursting", "pipebursting", "pipebursting", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/pipebursting")
        self.add_option("renovatie-door-lining-met-TUB-met-structureel-onvoldoende-reststerkte", "renovatie door lining met TUB met structureel onvoldoende reststerkte", "Renovatie door lining met TUB met structureel onvoldoende reststerkte", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/renovatie-door-lining-met-TUB-met-structureel-onvoldoende-reststerkte")
        self.add_option("renovatie-door-lining-met-TUB-met-structureel-voldoende-reststerkte", "renovatie door lining met TUB met structureel voldoende reststerkte", "Renovatie door lining met TUB met structureel voldoende reststerkte", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/renovatie-door-lining-met-TUB-met-structureel-voldoende-reststerkte")
        self.add_option("renovatie-door-middel-van-solventvrije-vezelversterkte-kunstharsen", "renovatie door middel van solventvrije vezelversterkte kunstharsen", "Renovatie door middel van solventvrije vezelversterkte kunstharsen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/renovatie-door-middel-van-solventvrije-vezelversterkte-kunstharsen")
        self.add_option("renovatie-stroomprofiel-met-buis-in-buissysteem-met-GVP-elementen", "renovatie stroomprofiel met buis in buissysteem met GVP-elementen", "Renovatie stroomprofiel met buis in buissysteem met GVP-elementen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/renovatie-stroomprofiel-met-buis-in-buissysteem-met-GVP-elementen")
        self.add_option("renovatie-stroomprofiel-met-buis-in-buissysteem-met-GVP-panelen", "renovatie stroomprofiel met buis in buissysteem met GVP-panelen", "Renovatie stroomprofiel met buis in buissysteem met GVP-panelen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/renovatie-stroomprofiel-met-buis-in-buissysteem-met-GVP-panelen")
        self.add_option("renovatie-volledige-leidingsectie-met-buis-in-buissysteem-met-GVP-elementen", "renovatie volledige leidingsectie met buis in buissysteem met GVP-elementen", "Renovatie volledige leidingsectie met buis in buissysteem met GVP-elementen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/renovatie-volledige-leidingsectie-met-buis-in-buissysteem-met-GVP-elementen")
        self.add_option("renovatie-volledige-leidingsectie-met-buis-in-buissysteem-met-GVP-panelen", "renovatie volledige leidingsectie met buis in buissysteem met GVP-panelen", "Renovatie volledige leidingsectie met buis in buissysteem met GVP-panelen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/renovatie-volledige-leidingsectie-met-buis-in-buissysteem-met-GVP-panelen")
        self.add_option("rioolrenovatie-d.m.v.-deelrenovatie-met-glasvezelversterkt-kunsthars", "rioolrenovatie d.m.v. deelrenovatie met glasvezelversterkt kunsthars", "Rioolrenovatie d.m.v. deelrenovatie met glasvezelversterkt kunsthars", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/rioolrenovatie-d.m.v.-deelrenovatie-met-glasvezelversterkt-kunsthars")
        self.add_option("rioolrenovatie-dmv-close-fit-lining-met-fabrieksmatig-gevouwen-HDPE-buizen-met-diameter", "rioolrenovatie dmv close-fit lining met fabrieksmatig gevouwen HDPE-buizen met diameter", "Rioolrenovatie dmv close-fit lining met fabrieksmatig gevouwen HDPE-buizen met diameter", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/rioolrenovatie-dmv-close-fit-lining-met-fabrieksmatig-gevouwen-HDPE-buizen-met-diameter")
        self.add_option("rioolrenovatie-door-middel-van-HDPE-grout-liner", "rioolrenovatie door middel van HDPE-grout liner", "Rioolrenovatie door middel van HDPE/grout liner", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/rioolrenovatie-door-middel-van-HDPE-grout-liner")
        self.add_option("uitwendige-aangepaste-PUR-bekleding-aangebracht-in-de-fabriek-voor-buizen-van-nodulair-gietijzer", "uitwendige aangepaste PUR-bekleding aangebracht in de fabriek voor buizen van nodulair gietijzer", "uitwendige aangepaste PUR-bekleding aangebracht in de fabriek voor buizen van nodulair gietijzer", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/uitwendige-aangepaste-PUR-bekleding-aangebracht-in-de-fabriek-voor-buizen-van-nodulair-gietijzer")
        self.add_option("uitwendige-beschermbanden-met-PE-inlage-aangebracht-in-de-fabriek-voor-buizen-van-nodulair-gietijzer", "uitwendige beschermbanden met PE-inlage aangebracht in de fabriek voor buizen van nodulair gietijzer", "uitwendige beschermbanden met PE-inlage aangebracht in de fabriek voor buizen van nodulair gietijzer", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/uitwendige-beschermbanden-met-PE-inlage-aangebracht-in-de-fabriek-voor-buizen-van-nodulair-gietijzer")
        self.add_option("uitwendige-geextrudeerde-PE-bekleding-aangebracht-in-de-fabriek-voor-buizen-van-nodulair-gietijzer", "uitwendige geextrudeerde PE-bekleding aangebracht in de fabriek voor buizen van nodulair gietijzer", "uitwendige geextrudeerde PE-bekleding aangebracht in de fabriek voor buizen van nodulair gietijzer", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/uitwendige-geextrudeerde-PE-bekleding-aangebracht-in-de-fabriek-voor-buizen-van-nodulair-gietijzer")
        self.add_option("uitwendige-waterdichte-PE-folie-op-de-werf-aangebracht-voor-buizen-van-nodulair-gietijzer", "uitwendige waterdichte PE-folie op de werf aangebracht voor buizen van nodulair gietijzer", "uitwendige waterdichte PE-folie op de werf aangebracht voor buizen van nodulair gietijzer", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/uitwendige-waterdichte-PE-folie-op-de-werf-aangebracht-voor-buizen-van-nodulair-gietijzer")
        self.add_option("waterdichting-door-middel-van-injectieharsen", "waterdichting door middel van injectieharsen", "Waterdichting door middel van injectieharsen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/waterdichting-door-middel-van-injectieharsen")
        self.add_option("waterdichting-door-middel-van-injectieharsen-in-man-toegankelijke-riolen", "waterdichting door middel van injectieharsen in man-toegankelijke riolen", "Waterdichting door middel van injectieharsen in man-toegankelijke riolen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/waterdichting-door-middel-van-injectieharsen-in-man-toegankelijke-riolen")
        self.add_option("waterdichting-van-lekkende-voegverbindingen-van-ronde-buizen-dmv-manchette", "waterdichting van lekkende voegverbindingen van ronde buizen dmv manchette", "Waterdichting van lekkende voegverbindingen van ronde buizen dmv manchette", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/waterdichting-van-lekkende-voegverbindingen-van-ronde-buizen-dmv-manchette")
        self.add_option("waterdichting-van-lekkende-voegverbindingen-van-ronde-buizen-dmv-uitwendige-krimpmof", "waterdichting van lekkende voegverbindingen van ronde buizen dmv uitwendige krimpmof", "Waterdichting van lekkende voegverbindingen van ronde buizen dmv uitwendige krimpmof", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlBuisbekledingUitvoeringswijze/waterdichting-van-lekkende-voegverbindingen-van-ronde-buizen-dmv-uitwendige-krimpmof")
