from OTLModel.Datatypes.Keuzelijst import Keuzelijst


# Generated with OTLEnumerationCreator
class KlFiguratieCode(Keuzelijst):
    """Codes voor de figuratie markering."""

    def __init__(self):
        super().__init__(naam="KlFiguratieCode",
                         label="Figuratie code",
                         uri="https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KlFiguratieCode",
                         definition="Codes voor de figuratie markering.",
                         usagenote="",
                         deprecated_version="",
                         codelist="https://wegenenverkeer.data.vlaanderen.be/id/conceptscheme/KlFiguratieCode")

        self.add_option("BBK-BLOK", "BBK BLOK", "Aanduiding bebouwde kom met blokken.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/BBK-BLOK")
        self.add_option("BBK-50", "BBK-50", "Aanduiding bebouwde kom met blokken met snelheidsbeperking van 50", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/BBK-50")
        self.add_option("PL-A", "PL-A", "Een voorsorteringspijl rechtdoor waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-A")
        self.add_option("PL-A'", "PL-A'", "Een voorsorteringspijl rechtdoor waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-A'")
        self.add_option("PL-B1'", "PL-B1'", "Een voorsorteringspijl rechtdoor + links waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-B1'")
        self.add_option("PL-B1", "PL-B1", "Een voorsorteringspijl rechtdoor + links waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-B1")
        self.add_option("PL-B2'", "PL-B2'", "Een voorsorteringspijl rechtdoor + rechts waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-B2'")
        self.add_option("PL-B2", "PL-B2", "Een voorsorteringspijl rechtdoor + rechts waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-B2")
        self.add_option("PL-C1", "PL-C1", "Een voorsorteringspijl links waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C1")
        self.add_option("PL-C1'", "PL-C1'", "Een voorsorteringspijl links waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C1'")
        self.add_option("PL-C2", "PL-C2", "Een voorsorteringspijl rechts waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C2")
        self.add_option("PL-C2'", "PL-C2'", "Een voorsorteringspijl rechts waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C2'")
        self.add_option("PL-C3", "PL-C3", "Een voorsorteringspijl 2de links waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C3")
        self.add_option("PL-C3'", "PL-C3'", "Een voorsorteringspijl 2de links waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C3'")
        self.add_option("PL-C4", "PL-C4", "Een voorsorteringspijl 2de rechts waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C4")
        self.add_option("PL-C4'", "PL-C4'", "Een voorsorteringspijl 2de rechts waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C4'")
        self.add_option("PL-C3-oud", "PL-C3 oud", "Een voorsorteringspijl 2de links waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C3-oud")
        self.add_option("PL-C3'-oud", "PL-C3' oud", "Een voorsorteringspijl 2de links waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C3'-oud")
        self.add_option("PL-C4-oud", "PL-C4 oud", "Een voorsorteringspijl 2de rechts waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C4-oud")
        self.add_option("PL-C4'-oud", "PL-C4' oud", "Een voorsorteringspijl 2de rechts waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-C4'-oud")
        self.add_option("PL-D", "PL-D", "Een voorsorteringspijl links + rechts waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-D")
        self.add_option("PL-D'", "PL-D'", "Een voorsorteringspijl links + rechts waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-D'")
        self.add_option("PL-E", "PL-E", "Een voorsorteringspijl rechtdoor + links + rechts waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-E")
        self.add_option("PL-E'", "PL-E'", "Een voorsorteringspijl rechtdoor + links + rechts waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-E'")
        self.add_option("PL-F1-oud", "PL-F1-oud", "Een voorsorteringspijl links waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F1-oud")
        self.add_option("PL-F1'-oud", "PL-F1'-oud", "Een voorsorteringspijl links waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F1'-oud")
        self.add_option("PL-F2-oud", "PL-F2-oud", "Een voorsorteringspijl rechts waar een snelheidsbeperking <= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F2-oud")
        self.add_option("PL-F2'-oud", "PL-F2'-oud", "Een voorsorteringspijl rechts waar een snelheidsbeperking >= 70 km/h geldt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F2'-oud")
        self.add_option("PL-G1", "PL-G1", "Een rijstrookverminderingspijl links voor autosnelwegen.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-G1")
        self.add_option("PL-G2", "PL-G2", "Een rijstrookverminderingspijl rechts voor autosnelwegen.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-G2")
        self.add_option("PL-G3", "PL-G3", "Een rijstrookverminderingspijl links voor niet-autosnelwegen.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-G3")
        self.add_option("PL-oud", "PL-oud", "Een fietspadpijl.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-oud")
        self.add_option("PL-h", "PL-h", "Een kleine dubbele fietspadpijl.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-h")
        self.add_option("PL-c1", "PL-c1", "Een voorsorteringspijl voor fietsers links.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-c1")
        self.add_option("PL-F1", "PL-F1", "Een voorsorteringspijl voor rotonde links.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F1")
        self.add_option("PL-F4", "PL-F4", "Een voorsorteringspijl voor rotonde rechtdoor + links.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F4")
        self.add_option("PL-F6", "PL-F6", "Een voorsorteringspijl voor rotonde rechtdoor + links + rechts.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F6")
        self.add_option("PL-F2", "PL-F2", "Een voorsorteringspijl voor rotonde rechtdoor.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F2")
        self.add_option("PL-F3", "PL-F3", "Een voorsorteringspijl voor rotonde rechts.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F3")
        self.add_option("PL-F5", "PL-F5", "Een voorsorteringspijl voor rotonde rechtdoor + rechts.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-F5")
        self.add_option("BUS-DW", "BUS DW", "Een dwarse lettermarkering BUS op de busstrook.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/BUS-DW")
        self.add_option("BUS-BOB-DW", "BUS BOB DW", "Een dwarse lettermarkering BUS op BOB.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/BUS-BOB-DW")
        self.add_option("BUS-BOB-LS", "BUS BOB LS", "Een overlangse lettermarkering BUS op BOB.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/BUS-BOB-LS")
        self.add_option("TAXI-DW", "TAXI DW", "Een dwarse lettermarkering TAXI.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/TAXI-DW")
        self.add_option("TAXI-LS", "TAXI LS", "Een overlangse lettermarkering TAXI.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/TAXI-LS")
        self.add_option("TRAM-DW", "TRAM DW", "Een dwarse lettermarkering TRAM.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/TRAM-DW")
        self.add_option("TRAM-LS", "TRAM LS", "Een overlangse lettermarkering TRAM.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/TRAM-LS")
        self.add_option("STOP-DW", "STOP DW", "Een dwarse lettermarkering STOP.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/STOP-DW")
        self.add_option("STOP-DW-oud", "STOP DW-oud", "Een dwarse lettermarkering STOP.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/STOP-DW-oud")
        self.add_option("BHALTE-GR", "BHALTE-GR", "Een lettermarkering BUS met arcering > 22.75 m².", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/BHALTE-GR")
        self.add_option("BHALTE-KL", "BHALTE-KL", "Een lettermarkering BUS met arcering < 22.75 m².", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/BHALTE-KL")
        self.add_option("BHALTE-WEG", "BHALTE-WEG", "Een lettermarkering BUS zonder arcering", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/BHALTE-WEG")
        self.add_option("VB-E1", "VB-E1", "Een verkeersbordmarkering parkeerverbod (OFF)", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/VB-E1")
        self.add_option("VB-A23", "VB-A23", "Een verkeersbordmarkering schoolkinderen (OFF)", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/VB-A23")
        self.add_option("VB-E9i", "VB-E9i", "Een verkeersbordmarkering parkeerschijf (OFF)", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/VB-E9i")
        self.add_option("LG-FIETS-GR", "LG-FIETS-GR", "Een fietslogomarkering groot.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-FIETS-GR")
        self.add_option("LG-FIETS-KL", "LG-FIETS-KL", "Een fietslogomarkering klein.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-FIETS-KL")
        self.add_option("LG-MV-KL", "LG-MV-KL", "Een mindervalidenlogo klein.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-MV-KL")
        self.add_option("LG-MV-N", "LG-MV-N", "Een mindervalidenlogo normaal.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-MV-N")
        self.add_option("LG-MV-GR", "LG-MV-GR", "Een mindervalidenlogo groot.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-MV-GR")
        self.add_option("visgraat", "visgraat", "Een visgraatmarkering om de verkeersveiligheid te vergroten en kop-staartbotsingen te vermijden (bij mist).", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/visgraat")
        self.add_option("VB-B1-GR", "VB-B1-GR", "Een omgekeerde driehoekmarkering groot.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/VB-B1-GR")
        self.add_option("VB-B1-KL", "VB-B1-KL", "Een omgekeerde driehoekmarkering klein.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/VB-B1-KL")
        self.add_option("VB-A49", "VB-A49", "Kruising sporen.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/VB-A49")
        self.add_option("VB-A21", "VB-A21", "Oversteekplaats voor voetgangers.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/VB-A21")
        self.add_option("VB-F113", "VB-F113", "Fietsstraat einde.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/VB-F113")
        self.add_option("VB-F111", "VB-F111", "Fietsstraat begin.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/VB-F111")
        self.add_option("LG-Brfiets-KL", "LG-Brfiets-KL", "Logo bromfiets klein.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-Brfiets-KL")
        self.add_option("LG-Brfiets-GR", "LG-Brfiets-GR", "Logo bromfiets groot.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-Brfiets-GR")
        self.add_option("LG-Autocar", "LG-Autocar", "Logo autocar", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-Autocar")
        self.add_option("LG-Woonwrk", "LG-Woonwrk", "Logo woon-werkverkeer.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-Woonwrk")
        self.add_option("LG-Elek-KL", "LG-Elek-KL", "Elektrische voertuigen logo verkleind.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-Elek-KL")
        self.add_option("LG-Elek-N", "LG-Elek-N", "Elektrische voertuigen logo normaal.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-Elek-N")
        self.add_option("LG-Elek-GR", "LG-Elek-GR", "Elektrische voertuigen logo vergroot.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/LG-Elek-GR")
        self.add_option("HM", "HM", "Referentiepuntmarkering hectometer- en kilometeraanduiding.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/HM")
        self.add_option("PL-G4", "PL-G4", "Een rijstrookverminderingspijl rechts voor niet-autosnelwegen.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlFiguratieCode/PL-G4")
