from OTLModel.Datatypes.Keuzelijst import Keuzelijst


# Generated with OTLEnumerationCreator
class KlLEKantopsluitingBijkomendeParameter(Keuzelijst):
    """Gedetailleerder typeren van de kantopsluiting."""

    def __init__(self):
        super().__init__(naam="KlLEKantopsluitingBijkomendeParameter",
                         label="Kantopsluiting bijkomende parameter",
                         uri="https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KlLEKantopsluitingBijkomendeParameter",
                         definition="Gedetailleerder typeren van de kantopsluiting.",
                         usagenote="",
                         deprecated_version="",
                         codelist="https://wegenenverkeer.data.vlaanderen.be/id/conceptscheme/KlLEKantopsluitingBijkomendeParameter")

        self.add_option("eindschikking-voor-schampkant", "eindschikking voor schampkant", "eindschikking voor schampkant", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/eindschikking-voor-schampkant")
        self.add_option("gebogen-trottoirband-of-Trottoirband-watergreppel-straal-kleiner-of-gelijk-5m-reflectoren-schuin", "gebogen trottoirband of Trottoirband-watergreppel straal kleiner of gelijk 5m reflectoren schuin", "Gebogen trottoirband of trottoirband-watergreppel, met straal kleiner of gelijk aan 5m en schuin geplaatste reflectoren.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/gebogen-trottoirband-of-Trottoirband-watergreppel-straal-kleiner-of-gelijk-5m-reflectoren-schuin")
        self.add_option("gebogen-trottoirband-of-Trottoirband-watergreppel-straal-kleiner-of-gelijk-5m", "gebogen trottoirband of Trottoirband-watergreppel straal kleiner of gelijk 5m", "gebogen trottoirband of trottoirband-watergreppel, met straal kleiner of gelijk aan 5m", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/gebogen-trottoirband-of-Trottoirband-watergreppel-straal-kleiner-of-gelijk-5m")
        self.add_option("rechte-schampkant", "rechte schampkant", "rechte schampkant", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/rechte-schampkant")
        self.add_option("supplement-voor-in-verstek-zagen", "supplement voor in verstek zagen", "supplement voor in verstek zagen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/supplement-voor-in-verstek-zagen")
        self.add_option("gebogen-trottoirband-of-Trottoirband-watergreppel-straal-groter-5m-reflectoren-schuin", "gebogen trottoirband of Trottoirband-watergreppel straal groter 5m reflectoren schuin", "Gebogen trottoirband of trottoirband-watergreppel, met straal groter dan 5 m met schuin geplaatste reflectoren.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/gebogen-trottoirband-of-Trottoirband-watergreppel-straal-groter-5m-reflectoren-schuin")
        self.add_option("gebogen-kantstrook-of-watergreppel-straal-groter-5m", "gebogen kantstrook of watergreppel straal groter 5m", "gebogen kantstrook of watergreppel, met straal groter dan 5m", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/gebogen-kantstrook-of-watergreppel-straal-groter-5m")
        self.add_option("rechte-kantstrook-of-watergreppel", "rechte kantstrook of watergreppel", "Rechte kantstrook of watergreppel.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/rechte-kantstrook-of-watergreppel")
        self.add_option("hoekstukken.-hoek-verschillend-90°-of-270°", "hoekstukken. hoek verschillend 90° of 270°", "Hoekstukken, hoek verschillend van 90° of 270°", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/hoekstukken.-hoek-verschillend-90°-of-270°")
        self.add_option("rechte-trottoirband-of-trottoirband-watergreppel", "rechte trottoirband of trottoirband-watergreppel", "Rechte trottoirband of trottoirband-watergreppel.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/rechte-trottoirband-of-trottoirband-watergreppel")
        self.add_option("hoekstukken.-hoek-90°-of-270°", "hoekstukken. hoek 90° of 270°", "hoekstukken waarbij de hoek gelijk is aan 90° of 270°", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/hoekstukken.-hoek-90°-of-270°")
        self.add_option("trottoirbanden-voor-minder-validen", "trottoirbanden voor minder-validen", "trottoirbanden voor minder-validen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/trottoirbanden-voor-minder-validen")
        self.add_option("rechte-trottoirband-of-trottoirbandwater-greppel-reflectoren-verticaal", "rechte trottoirband of trottoirbandwater-greppel reflectoren verticaal", "Rechte trottoirband of trottoirband-watergreppel met verticaal geplaatste reflectoren.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/rechte-trottoirband-of-trottoirbandwater-greppel-reflectoren-verticaal")
        self.add_option("rechte-trottoirband-of-Trottoirband-watergreppel-reflectoren-schuin", "rechte trottoirband of Trottoirband-watergreppel reflectoren schuin", "Rechte trottoirband of trottoirband-watergreppel met schuin geplaatste reflectoren.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/rechte-trottoirband-of-Trottoirband-watergreppel-reflectoren-schuin")
        self.add_option("gebogen-trottoirband-of-Trottoirband-watergreppel-straal-groter-5m", "gebogen trottoirband of Trottoirband-watergreppel straal groter 5m", "Gebogen trottoirband of trottoirband-watergreppel, met straal groter dan 5 m.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/gebogen-trottoirband-of-Trottoirband-watergreppel-straal-groter-5m")
        self.add_option("gebogen-trottoirband-of-Trottoirband-watergreppel-straal-groter-5m-reflectoren-verticaal", "gebogen trottoirband of Trottoirband-watergreppel straal groter 5m reflectoren verticaal", "Gebogen trottoirband of trottoirband-watergreppel, met straal groter dan 5 m met verticaal geplaatste reflectoren.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/gebogen-trottoirband-of-Trottoirband-watergreppel-straal-groter-5m-reflectoren-verticaal")
        self.add_option("gebogen-kantstrook-of-watergreppel-straal-kleiner-of-gelijk-5m", "gebogen kantstrook of watergreppel straal kleiner of gelijk 5m", "gebogen kantstrook of watergreppel, met straal kleiner of gelijk 5m", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/gebogen-kantstrook-of-watergreppel-straal-kleiner-of-gelijk-5m")
        self.add_option("gebogen-trottoirband-of-Trottoirband-watergreppel-straal-kleiner-of-gelijk-5m-reflectoren-verticaal", "gebogen trottoirband of Trottoirband-watergreppel straal kleiner of gelijk 5m reflectoren verticaal", "Gebogen trottoirband of trottoirband-watergreppel, met straal kleiner of gelijk aan 5m met verticaal geplaatste reflectoren.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/gebogen-trottoirband-of-Trottoirband-watergreppel-straal-kleiner-of-gelijk-5m-reflectoren-verticaal")
        self.add_option("overgangstrottoirbanden", "overgangstrottoirbanden", "Overgangstrottoirbanden", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlLEKantopsluitingBijkomendeParameter/overgangstrottoirbanden")
