# coding=utf-8
from OTLModel.Datatypes.Keuzelijst import Keuzelijst


# Generated with OTLEnumerationCreator. To modify: extend, do not edit
class KlNSB(Keuzelijst):
    """Het mogelijke huidige natuurbeelden of natuurstreefbeelden."""

    def __init__(self):
        super().__init__(naam="KlNSB",
                         label="Natuurstreefbeeld",
                         objectUri="https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KlNSB",
                         definition="Het mogelijke huidige natuurbeelden of natuurstreefbeelden.",
                         usagenote="",
                         deprecated_version="",
                         codelist="https://wegenenverkeer.data.vlaanderen.be/id/conceptscheme/KlNSB")

        self.add_option("2130", "2130", "zanddoddengras, kleverige reigersbek, ruw vergeet-mij-nietje, kruipend stalkruid, zandhoornbloem, duinfakkelgras, liggende asperge, duindravik, duinviooltje, kegelsilene, ruwe klaver, duin- en gewimperd langbaardgras, lathyruswikke, geel walstro, grote tijm, geel zonneroosje, liggend bergvlas, nachtsilene, walstrobremraap, kalkbedstro, zachte haver, voorjaarsganzerik, duindravik, gestreepte klaver, wondklaver", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/2130")
        self.add_option("2330", "2330", "vroege haver, klein vogelpootje, zilverhaver, klein tasjeskruid, dwergviltkruid, eekhoorngras, zandblauwtje, veldereprijs, hazenpootje, eenjarige hardbloem, rode schijnspurrie, akkerviooltje, zandmuur, reigersbek, spurrie, straatgras, zandraket, vroegeling, kleine leeuwenklauw, zachte ooievaarsbek, klein streepzaad, gewoon langbaardgras, zandhoornbloem, slofhak ", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/2330")
        self.add_option("4030", "4030", "meidoorn spp., sleedoorn en rozen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/4030")
        self.add_option("6120", "6120", "cipreswolfsmelk, geoorde zuring, gestreepte klaver, grote tijm, handjesgras, harige ratelaar, hemelsleutel, kaal breukkruid, kleine pimpernel, kleine ratelaar, knikkende distel, knolbeemdgras, kruisdistel, kweekdravik, moeslook, ronde ooievaarsbek, rozetkruidkers, rozetsteenkers, sikkelklaver, slangenlook, smalle raai, tripmadam, veldsalie, viltganzerik, voorjaarszegge, wit en zacht vetkruid, zachte haver, zeepkruid", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/6120")
        self.add_option("6210-Hk", "6210 Hk", "blauwgras, bergdravik, duifkruid, grote centaurie, ruige scheefkelk, geel zonneroosje, kleine pimpernel, Kalkwalstro, gevinde kortsteel, aarddistel, smal fakkelgras, driedistel", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/6210-Hk")
        self.add_option("6230-Ha", "6230 Ha", "Idem als hierboven maar met 3 soorten aanwezig uit: bosdroogbloem, dicht havikskruid, dwergviltkruid, eekhoorngras, geel walstro, grasklokje, steenanjer, viltganzerik, kleine tijm, zandblauwtje", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/6230-Ha")
        self.add_option("6230-Hmo", "6230 Hmo", "blauwe knoop, blauwe zegge, bleeksporig bosviooltje, bleke zegge, borstelgras, dicht havikskruid, echte guldenroede, fijn schapengras, fraai hertshooi, gelobde maanvaren, gevlekte orchis, heidekartelblad, hondsviooltje, kleine tijm, klokjesgentiaan, knollathyrus, kruipganzerik, liggend walstro, liggende vleugeltjesbloem, mannetjesereprijs, spits havikskruid, stijf havikskruid, stijve ogentroost, tandjesgras, tormentil, trekrus, tweenervige zegge, veelbloemige veldbies, zaagblad, klokjesgentiaan, heidekartelblad, welriekende nachtorchis", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/6230-Hmo")
        self.add_option("6230-Hn", "6230 Hn", "blauwe knoop, blauwe zegge, bleeksporig bosviooltje, bleke zegge, borstelgras, dicht havikskruid, echte guldenroede, fijn schapengras, fraai hertshooi, gelobde maanvaren, gevlekte orchis, heidekartelblad, hondsviooltje, kleine tijm, klokjesgentiaan, knollathyrus, kruipganzerik, liggend walstro, liggende vleugeltjesbloem, mannetjesereprijs, spits havikskruid, stijf havikskruid, stijve ogentroost, tandjesgras, tormentil, trekrus, tweenervige zegge, veelbloemige veldbies, zaagblad, klokjesgentiaan, heidekartelblad, welriekende nachtorchis", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/6230-Hn")
        self.add_option("6430", "6430", "oeverzegge, moeraszegge, gele lis, wolfspoot, hop, harig wilgenroosje, gewone smeerwortel, haagwinde, moerasandoorn, groot hoefblad, koninginnenkruid, grote kattenstaart, geoord helmkruid, gevleugeld helmkruid, viltige bastaardwederik, groot warkruid, moerasmelkdistel en heemst", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/6430")
        self.add_option("6510Hu", "6510Hu", "aardaker, beemdkroon, beemdooievaarsbek, bevertjes, gele morgenster, gewone agrimonie, gewone rolklaver, gewone vogelmelk, glad walstro, goudhaver, graslathyrus, groot streepzaad, grote bevernel, grote pimpernel, gulden boterbloem, gulden sleutelbloem, klavervreter, kleine bevernel, kleine ratelaar, knolboterbloem, knolsteenbreek, knoopkruid, kraailook, margriet, muskuskaasjeskruid, naakte lathyrus, rapunzelklokje, ruige leeuwentand, veldlathyrus, veldsalie, vijfdelig kaasjeskruid en zachte haver, grote ratelaar, vertakte leeuwentand, vierzadige wikke", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/6510Hu")
        self.add_option("6510Huk", "6510Huk", "aarddistel, beemdkroon, bevertjes, driedistel, duifkruid, geelhartje, gevinde kortsteel, gewone agrimonie, goudhaver, grote tijm, gulden sleutelbloem, kattendoorn, kleine bevernel, kleine pimpernel, knolboterbloem, kruipend stalkruid, ruige leeuwentand, ruige weegbree, voorjaarszegge, wilde marjolein, zachte haver, zeegroene zegge", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/6510Huk")
        self.add_option("9110", "9110", "Veldbies-Beukenbossen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/9110")
        self.add_option("9120", "9120", "Eiken-Beukenbossen op zure bodems ", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/9120")
        self.add_option("9130", "9130", "Eiken-Beukenbossen met Wilde hyacint en ParelgrasBeukenbossen", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/9130")
        self.add_option("9150", "9150", "9150", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/9150")
        self.add_option("9160", "9160", "Essen-Eikenbossen zonder Wilde hyacint", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/9160")
        self.add_option("9190", "9190", "Oude Eiken-Berkenbossen op zeer voedselarm zand", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/9190")
        self.add_option("91E0", "91E0", "grove den (min 50% van de boomlaag) + > 0,5 ha + oud bos + kenmerkende soorten: Lelietje-van-dalen, dalkruid, ruige veldbies, bosgierstgras, hulst, wilde kamperfoelie, gladde witbol, dubbelloof, valse salie, pilzegge, adelaarsvaren, grote veldbies, witte veldbies, gewone salomonszegel, bosanemoon, witte klaverzurig", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/91E0")
        self.add_option("andere-Cd", "andere Cd", "andere cd", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Cd")
        self.add_option("andere-Cm", "andere Cm", "andere cm", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Cm")
        self.add_option("andere-Cp", "andere Cp", "struikheide, dopheide, blauwe bosbes, stekelbrem, kruipbrem", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Cp")
        self.add_option("andere-Ha", "andere Ha", "akkerhoornbloem, gewone veldbies, gewoon biggenkruid, gewoon duizendblad, gewoon struisgras, hazenpootje, klein vogelpootje, kleine klaver, kleine leeuwentand, knolboterbloem, muizenoor, schapenzuring, smalle weegbree, vroege haver, zilverhaver", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Ha")
        self.add_option("andere-Hj", "andere Hj", "andere hj", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Hj")
        self.add_option("andere-Hp", "andere Hp", "geen soorten van de twee volgende types (rbbkam & rbbvos) aanwezig.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Hp")
        self.add_option("andere-Hr", "andere Hr", "grote brandnetel, kleefkruid, ridderzuring, akkerdistel, speerdistel, gewone berenklauw, fluitenkruid, bramen, klit, jacobskruiskruid, ijle dravik, dolle kervel, kweek, kropaar, haagwinde, zevenblad", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Hr")
        self.add_option("andere-Hu", "andere Hu", "Voldoet niet aan de voorwaarden voor 6510 (< 7 soorten uit 6510)", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Hu")
        self.add_option("andere-Mr", "andere Mr", "riet en soorten uit R3", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Mr")
        self.add_option("andere-Sz", "andere Sz", "Andere Sz", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/andere-Sz")
        self.add_option("rbbha", "rbbha", "Soortenrijk struisgrasland met vrij algemene soorten", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbha")
        self.add_option("rbbhc", "rbbhc", "echte koekoeksbloem, grote ratelaar, kruipend zenegroen, moeras/zompvergeet-me-nietje, dotterbloem, kale jonker, lidrus, moerasrolklaver, moeraswalstro, egelboterbloem, pinksterbloem, slanke sleutelbloem, tweerijige zegge, gewone waterbies, heelblaadjes, penningkruid, pijptorkruid, zomprus", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbhc")
        self.add_option("rbbhf", "rbbhf", "wilde bertram, grote wederik, melkeppe, hennegras, ruw walstro, wateraardbei, moerasbeemdgras, veenpluis, veenmos en/of zwarte zegge, moerasspirea", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbhf")
        self.add_option("rbbhu", "rbbhu", "min. 2 soorten abundant aanwezig uit:  kruipend zenegroen, pinksterbloem, tweerijige zegge, moesdistel, ruwe smele, lidrus, moerasspirea, beemdlangbloem, moerasrolklaver, echte koekoeksbloem, penningkruid, moeras/zompvergeet-mij-nietje, grote ratelaar, waterkruiskruid, smeerwortel, vogelwikke OF trosdravik of grote trosdravik aanwezig", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbhu")
        self.add_option("rbbkam", "rbbkam", "kamgras en/of veldgerst abundant én aantal soorten >;15", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbkam")
        self.add_option("rbbmr", "rbbmr", "riet en soorten uit R3; kenmerken en kenmerkende soorten voor rbbmr worden in 2017 door INBO uitgewerkt.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbmr")
        self.add_option("rbbppm", "rbbppm", "Structuurrijke, oude bestanden van Grove den met een minimale leeftijd van tachtig jaar.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbppm")
        self.add_option("rbbsf", "rbbsf", "Boomlaag zoals hierboven + opp > 0,5 ha + oud bos met kenmerkende soorten van oud bos (bijlage 3), schraalland of heide (verder te bepalen met Bossleutel) ", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbsf")
        self.add_option("rbbsg", "rbbsg", "Dit type staat voor begroeiingen waar Brem veel voorkomt of domineert. Soms komt ook de veel zeldzamere Gaspeldoorn voor. Bremstruwelen bedekken zelden volledige percelen.", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbsg")
        self.add_option("rbbsp", "rbbsp", "Dit zijn struwelen die gedomineerd worden door houtige, doornige soorten zoals Sleedoorn, meidoorn (eenstijlige en tweestijlige) en/of rozen. We vinden dedoornige struwelen vooral terug als houtkanten en uitgegroeide hagen. ", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbsp")
        self.add_option("rbbzil", "rbbzil", "zilt grasland: aardbeiklaver, akkerkers, getand vlotgras, gewone waterbies, heelblaadjes, klein vlooienkruid, kruipend moerasscherm, moeras/zompvergeetme-nietje, moeraszoutgras (polderstreek), penningkruid, pijptorkruid, platte rus, polei, rode ogentroost, slanke waterbies, smalle rolklaver (polderstreek), valse voszegge, watermunt, zeegroene rus, zilte rus, zilte zegge (polderstreek), zilverschoon, zomprus", "https://wegenenverkeer.data.vlaanderen.be/id/concept/KlNSB/rbbzil")
